fastcgi++: Fastcgipp::Fcgistream< charT, traits > Class Template Reference
Fastcgipp::Fcgistream< charT, traits > Class Template Reference
Stream class for output of client data through FastCGI.
#include <fcgistream.hpp>
Classes
class Fcgibuf
Stream buffer class for output of client data through FastCGI.
Public Member Functions
Fcgistream ()
void set (Protocol::FullId id_, Transceiver &transceiver_, Protocol::RecordType type_)
Arguments passed directly to Fcgibuf::set().
void dump (char *data, size_t size)
Dumps raw data directly into the FastCGI protocol.
void dump (std::basic_istream< char > &stream)
Dumps an input stream directly into the FastCGI protocol.
Private Attributes
Fcgibuf buffer
Stream buffer object.
Detailed Description
template<class charT, class traits>
class Fastcgipp::Fcgistream< charT, traits >
Stream class for output of client data through FastCGI.
This class is derived from std::basic_ostream<charT, traits>. It acts just the same as any stream does with the added feature of the dump() function.
Template Parameters:
charT Character type (char or wchar_t)
traits Character traits
Definition at line 43 of file fcgistream.hpp.
Constructor & Destructor Documentation
template<class charT , class traits > Fastcgipp::Fcgistream< charT, traits >::Fcgistream () [inline]
Definition at line 46 of file fcgistream.hpp.
Member Function Documentation
template<class charT , class traits > void Fastcgipp::Fcgistream< charT, traits >::dump (std::basic_istream< char > & stream) [inline]
Dumps an input stream directly into the FastCGI protocol.
This function exists as a mechanism to dump a raw input stream out this stream bypassing the stream buffer or any code conversion mechanisms. Typically this would be a filestream associated with an image or something. The stream is transmitted until an EOF.
Parameters:
[in] stream Reference to input stream that should be transmitted.
Definition at line 165 of file request.cpp.
References Fastcgipp::Fcgistream< charT, traits >::buffer, and Fastcgipp::Fcgistream< charT, traits >::dump().
template<class charT , class traits > void Fastcgipp::Fcgistream< charT, traits >::dump (char * data, size_t size) [inline]
Dumps raw data directly into the FastCGI protocol.
This function exists as a mechanism to dump raw data out the stream bypassing the stream buffer or any code conversion mechanisms. If the user has any binary data to send, this is the function to do it with.
Parameters:
[in] data Pointer to first byte of data to send
[in] size Size in bytes of data to be sent
Definition at line 59 of file fcgistream.hpp.
Referenced by Fastcgipp::Fcgistream< charT, traits >::dump().
template<class charT , class traits > void Fastcgipp::Fcgistream< charT, traits >::set (Protocol::FullId id_, Transceiver & transceiver_, Protocol::RecordType type_) [inline]
Arguments passed directly to Fcgibuf::set().
Definition at line 48 of file fcgistream.hpp.
Referenced by Fastcgipp::Request< charT >::set().
Member Data Documentation
template<class charT , class traits > Fcgibuf Fastcgipp::Fcgistream< charT, traits >::buffer [private]
Stream buffer object.
Definition at line 141 of file fcgistream.hpp.
Referenced by Fastcgipp::Fcgistream< charT, traits >::dump(), Fastcgipp::Fcgistream< charT, std::char_traits< charT > >::dump(), and Fastcgipp::Fcgistream< charT, std::char_traits< charT > >::set().
The documentation for this class was generated from the following files:
fcgistream.hpp
request.cpp