fastcgi++: utf8_codecvt_facet Struct Reference
utf8_codecvt_facet Struct Reference
#include <utf8_codecvt_facet.hpp>
Public Member Functions
utf8_codecvt_facet (std::size_t no_locale_manage=0)
Protected Member Functions
virtual std::codecvt_base::result do_in (std::mbstate_t &state, const char *from, const char *from_end, const char *&from_next, wchar_t *to, wchar_t *to_end, wchar_t *&to_next) const
virtual std::codecvt_base::result do_out (std::mbstate_t &state, const wchar_t *from, const wchar_t *from_end, const wchar_t *&from_next, char *to, char *to_end, char *&to_next) const
bool invalid_continuing_octet (unsigned char octet_1) const
bool invalid_leading_octet (unsigned char octet_1) const
int get_cont_octet_out_count (wchar_t word) const
virtual bool do_always_noconv () const throw ()
virtual std::codecvt_base::result do_unshift (std::mbstate_t &, char *from, char *, char *&next) const
virtual int do_encoding () const throw ()
virtual int do_length (BOOST_CODECVT_DO_LENGTH_CONST std::mbstate_t &, const char *from, const char *from_end, std::size_t max_limit) const
virtual int do_max_length () const throw ()
Static Protected Member Functions
static unsigned int get_cont_octet_count (unsigned char lead_octet)
static unsigned int get_octet_count (unsigned char lead_octet)
Detailed Description
Definition at line 113 of file utf8_codecvt_facet.hpp.
Constructor & Destructor Documentation
utf8_codecvt_facet::utf8_codecvt_facet (std::size_t no_locale_manage = 0) [inline, explicit]
Definition at line 117 of file utf8_codecvt_facet.hpp.
Member Function Documentation
virtual bool utf8_codecvt_facet::do_always_noconv () const throw () [inline, protected, virtual]
Definition at line 157 of file utf8_codecvt_facet.hpp.
virtual int utf8_codecvt_facet::do_encoding () const throw () [inline, protected, virtual]
Definition at line 171 of file utf8_codecvt_facet.hpp.
BOOST_UTF8_BEGIN_NAMESPACE std::codecvt_base::result utf8_codecvt_facet::do_in (std::mbstate_t & state, const char * from, const char * from_end, const char *& from_next, wchar_t * to, wchar_t * to_end, wchar_t *& to_next) const [protected, virtual]
Definition at line 34 of file utf8_codecvt_facet.cpp.
References get_cont_octet_count(), invalid_continuing_octet(), and invalid_leading_octet().
int utf8_codecvt_facet::do_length (BOOST_CODECVT_DO_LENGTH_CONST std::mbstate_t & , const char * from, const char * from_end, std::size_t max_limit) const [protected, virtual]
Definition at line 173 of file utf8_codecvt_facet.cpp.
virtual int utf8_codecvt_facet::do_max_length () const throw () [inline, protected, virtual]
Definition at line 190 of file utf8_codecvt_facet.hpp.
std::codecvt_base::result utf8_codecvt_facet::do_out (std::mbstate_t & state, const wchar_t * from, const wchar_t * from_end, const wchar_t *& from_next, char * to, char * to_end, char *& to_next) const [protected, virtual]
Definition at line 111 of file utf8_codecvt_facet.cpp.
References get_cont_octet_out_count().
virtual std::codecvt_base::result utf8_codecvt_facet::do_unshift (std::mbstate_t & , char * from, char * , char *& next) const [inline, protected, virtual]
Definition at line 160 of file utf8_codecvt_facet.hpp.
static unsigned int utf8_codecvt_facet::get_cont_octet_count (unsigned char lead_octet) [inline, static, protected]
Definition at line 147 of file utf8_codecvt_facet.hpp.
Referenced by do_in().
BOOST_UTF8_BEGIN_NAMESPACE int utf8_codecvt_facet::get_cont_octet_out_count (wchar_t word) const [protected]
Definition at line 262 of file utf8_codecvt_facet.cpp.
Referenced by do_out().
unsigned int utf8_codecvt_facet::get_octet_count (unsigned char lead_octet) [static, protected]
Definition at line 205 of file utf8_codecvt_facet.cpp.
bool utf8_codecvt_facet::invalid_continuing_octet (unsigned char octet_1) const [inline, protected]
Definition at line 137 of file utf8_codecvt_facet.hpp.
Referenced by do_in().
bool utf8_codecvt_facet::invalid_leading_octet (unsigned char octet_1) const [inline, protected]
Definition at line 141 of file utf8_codecvt_facet.hpp.
Referenced by do_in().
The documentation for this struct was generated from the following files:
utf8_codecvt_facet.hpp
utf8_codecvt_facet.cpp